# 项目相关配置
spring:
  application:
    #应用名
    name: weBot

  # 驼峰下划线转换
  jackson:
    property-naming-strategy: SNAKE_CASE

# 监听端口
server:
  port: 8080

# 日志
logging:
  level:
    com.base: @logging.level@
    org.springframework: warn
    tech.powerjob.worker.background: warn
    org.mybatis.spring.mapper: error
  config: classpath:logback.xml

jwt:
  header: "Authorization" #token返回头部
  secret: "1b1b553ded61cb43f225c01f3ae25eaf.XuybO9EEIm8wZHDH"  #密钥
  expireTime: 60000 #token有效时间 (分钟) 建议一小时以上